---
- hosts: localhost
  connection: local
  become: true  
  vars:
    user:
      - mark
      - marijkehuisman
      - fardau
      - desireerooks
      - myneketermaat
      - henniedijkstra
      
# Entirely for Ubuntu-based OS  

  tasks:
      
  - name: Create line in ~/.config/gtk-3.0/bookmarks
    lineinfile:
      path: /home/{{ user[5] }}/.config/gtk-3.0/bookmarks
      line: file:///mnt/Euphoria%20Drive
