---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Maak dconf local.d directory
    file:
      path: /etc/dconf/db/local.d
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: Maak profile directory
    file:
      path: /etc/dconf/profile
      state: directory
      owner: root
      group: root
      mode: '0755'
  
  - name: TEST Maak db file
    copy:
      dest: "/home/mark/test/dconf/profile/user"
      content: |
        user-db:user
        system-db:local
