---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: TEST Maak dconf local.d directory
    file:
      path: /home/mark/test/dconf/db/local.d
      state: directory
      owner: root
      group: root
      mode: '0755'
