---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Maak dconf local.d directory
    file:
      path: /etc/dconf/db/local.d
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: TEST Maak profile directory
    file:
      path: /etc/dconf/profile
      state: directory
      owner: root
      group: root
      mode: '0755'
  
  - name: TEST Maak db file
    copy:
      dest: "/etc/dconf/profile/user"
      content: |
        user-db:user
        system-db:local

  - name: Maak 00-background file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/00-background"
      content: |
        [org/gnome/desktop/background]
        color-shading-type='solid'
        picture-options='zoom'
        picture-uri='file:///usr/share/backgrounds/euphoria-wallpaper.png'
          
#als laatste
  - name: TEST run command dconf update
    command: dconf update
    
