---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installeer meerdere apt
    package:
      name:
        - htop

  - name: Installeer snaps
    snap:
      name:
        - bitwarden
