---
- hosts: localhost
  connection: local
  become: true  
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
  - name: Installeer packages
    package:
      name:
        - python3-psutil
        - curl
        - git
        - landscape-client
        - htop
        - lm-sensors
        - neofetch
        - gnome-tweaks

  - name: Installeer snaps
    snap:
      name:
        - bitwarden
        
  - name: Verwijderen ongewenste packages
    package: 
      name: 
        - gnome-initial-setup
      state: absent

  - name: Kopieer wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/euphoria-wallpaper.png
      owner: root
      group: root
            
  - name: Ansible gebruiker toevoegen voor cron
    user:
      name: systeemsletje
      system: yes

  - name: sudo instellingen voor systeemsletje
    copy:
      src: files/sudoer_systeemsletje
      dest: /etc/sudoers.d/systeemsletje
      owner: root
      group: root
      mode: 0440
      
  - name: Maak dconf local.d directory
    file:
      path: /etc/dconf/db/local.d
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: Maak dconf local.d/locks directory
    file:
      path: /etc/dconf/db/local.d/locks
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: Maak profile directory
    file:
      path: /etc/dconf/profile
      state: directory
      owner: root
      group: root
      mode: '0755'
  
  - name: Maak db file
    copy:
      dest: "/etc/dconf/profile/user"
      content: |
        user-db:user
        system-db:local

  - name: Maak 00-background file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/00-background"
      content: |
        [org/gnome/desktop/background]
        color-shading-type='solid'
        picture-options='zoom'
        picture-uri='file:///usr/share/backgrounds/euphoria-wallpaper.png'

  - name: Maak background lock-file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/locks/00-background"
      content: |
        /org/gnome/desktop/background/picture-uri
        
#als laatste
  - name: Run command dconf update
    command: dconf update

# Naam van de cronjob NIET veranderen      
  - name: Ansible-pull cron job
    cron: 
      name: Ansible automatiseren
      user: systeemsletje
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/mull0r/euphoria_workstation.git
