---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installeer packages
    package:
      name:
        - htop
        - lm-sensors
        - neofetch

  - name: Installeer snaps
    snap:
      name:
        - bitwarden
