---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installeer packages
    package:
      name:
        - python3-psutil
        - htop
        - lm-sensors
        - neofetch

  - name: Installeer snaps
    snap:
      name:
        - bitwarden

  - name: Kopieer wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/euphoria-wallpaper.png
      owner: root
      group: root
      
  - name: Wallpaper instellen
    become_user: mark
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/euphoria-wallpaper.png'"

  - name: Wallpaper positie instellen
    become_user: mark
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
