---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installeer meerdere apt
    package:
      name:
        - htop
        - lm-sensors
        - neofetch

  - name: Installeer snaps
    snap:
      name:
        - bitwarden

  - name: Kopieer wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/euphoria-wallpaper.png
      owner: root
      group: root
