---
- hosts: localhost
  connection: local
  become: true
  vars:
    user:
      - mark
      - marijkehuisman
      - fardau
      - desireerooks
      - myneketermaat
      - henniedijkstra
      - talysakatoele
  
# Entirely for Ubuntu-based OS
# Updated: 2022-04-26 - 13:26

  tasks:
  
  - include: tasks/packages.yml
  - include: tasks/dconf-initial-setup.yml
  - include: tasks/set-wallpaper.yml
  - include: tasks/favorite-apps.yml
  - include: tasks/general-settings.yml
  - include: tasks/mounting-home-and-drive.yml
  - include: tasks/bookmarks.yml
  
  - name: Copy fonts to system wide
    copy:
      src: files/fonts/
      dest: /usr/local/share/fonts
            
  - name: Add Ansible user for cron
    user:
      name: systeemsletje
      system: yes

  - name: sudo set for systeemsletje
    copy:
      src: files/sudoer_systeemsletje
      dest: /etc/sudoers.d/systeemsletje
      owner: root
      group: root
      mode: 0440

# Naam van de cronjob NIET veranderen      
  - name: Ansible-pull cron job
    cron: 
      name: Ansible automatiseren
      user: systeemsletje
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/mull0r/euphoria_workstation.git
      
  handlers: 
  - name: dconf update
    command: dconf update
