---
- hosts: local
  connection: local
  become_user: mark

  tasks:
  - name: Wallpaper instellen
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/euphoria-wallpaper.png'"

  - name: Wallpaper positie instellen
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
