---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  
  - name: Create Euphoria Drive folder
    file:
      path: "{{home}}/Euphoria Drive"
      state: directory
    become: true
    become_method: sudo
    become_user: "{{account}}"

