  - name: Maak dconf local.d directory
    file:
      path: /etc/dconf/db/local.d
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: Maak dconf local.d/locks directory
    file:
      path: /etc/dconf/db/local.d/locks
      state: directory
      owner: root
      group: root
      mode: '0755'
      
  - name: Maak profile directory
    file:
      path: /etc/dconf/profile
      state: directory
      owner: root
      group: root
      mode: '0755'
  
  - name: Maak db file
    copy:
      dest: "/etc/dconf/profile/user"
      content: |
        user-db:user
        system-db:local
