  - name: Create 00-favorite-apps file with content
    copy:
      dest: "/etc/dconf/db/local.d/00-favorite-apps"
      content: |
        [org/gnome/shell]
        favorite-apps = ['org.gnome.Nautilus.desktop', 'firefox_firefox.desktop', 'firefox.desktop', 'geary.desktop', 'libreoffice-writer.desktop', 'libreoffice-calc.desktop', 'gimp.desktop', 'bitwarden_bitwarden.desktop', 'gnome-control-center.desktop']
    notify: dconf update


  - name: Maak favorite-apps lock-file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/locks/00-favorite-apps"
      content: |
        /org/gnome/shell/favorite-apps
    notify: dconf update
