  - name: Installeer packages
    package:
      name:
        - git 
        - python3-psutil
        - curl
        - landscape-client
        - nfs-common
        - htop
        - lm-sensors
        - neofetch
        - gnome-tweaks
        - geary
        - timeshift
        - gimp
        - inkscape
        - scribus
        - printer-driver-dymo
      state: latest
      update_cache: yes

  - name: Installeer snaps
    snap:
      name:
        - bitwarden
        
  - name: Verwijderen ongewenste packages
    package: 
      name: 
        - gnome-initial-setup
        - teamviewer-host
      state: absent
