  - name: Create 00-screen-share file with content
    copy:
      dest: "/etc/dconf/db/local.d/00-screen-share"
      content: |
        [org/gnome/settings-daemon/plugins/sharing]
        active = true
    register: dconf
        
  - name: Maak favorite-apps lock-file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/locks/00-screen-share"
      content: |
        /org/gnome/settings-daemon/plugins/sharing/active
    register: dconf
    
    #als laatste
  - name: Run command dconf update
    command: dconf update
    when: dconf.changed
