  - name: Kopieer wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/euphoria-wallpaper.png
      owner: root
      group: root

  - name: Maak 00-background file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/00-background"
      content: |
        [org/gnome/desktop/background]
        color-shading-type='solid'
        picture-options='zoom'
        picture-uri='file:///usr/share/backgrounds/euphoria-wallpaper.png'
    register: dconf

  - name: Maak background lock-file met inhoud
    copy:
      dest: "/etc/dconf/db/local.d/locks/00-background"
      content: |
        /org/gnome/desktop/background/picture-uri
        /org/gnome/desktop/background/picture-options
    register: dconf
